name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@4ae8e7f0e21f5d6544eaaf9869c02716d5d13b2b # master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.REPO_HOST }}
      deploy-user: ${{ secrets.REPO_USER }}
      deploy-key: ${{ secrets.REPO_KEY }}
